homework2
marinamarinat/magic-ball pull request #5
Opened 2021-11-09 14:12 UTC by marinamarinat

2021-11-10 18:04 UTC, ios-school-yalantis requested changes

2021-11-10 18:04 UTC, ios-school-yalantis commented on magic 8 ball/NetworkService.swift
> +     func request(urlString: String, completion: @escaping (Magic?, Error?) -> Void) {
похоже лишний пробел в строке

2021-11-10 18:04 UTC, ios-school-yalantis commented on magic 8 ball/view controllers/AlertController.swift
> +    @objc func showAddAnswerAlert() {
должна ли функция быть `@objc` если возможно лучше убрать

2021-11-10 18:04 UTC, ios-school-yalantis commented on magic 8 ball/view controllers/AlertController.swift
> +        }
выглядит так что переход на DispatchQueue.main не нужен, так как мы уже в нем

2021-11-10 18:04 UTC, ios-school-yalantis commented on magic 8 ball/view controllers/SettingsViewController.swift
>      static var answers:[String] = []
по возможности нужно избавится от `static`

2021-11-10 21:24 UTC, marinamarinat commented on magic 8 ball/view controllers/AlertController.swift
> +    @objc func showAddAnswerAlert() {
если убрать @objc, то появляется ошибка: Argument of '#selector' refers to instance method 'showAddAnswerAlert()' that is not exposed to Objective-C

с этим что-то можно сделать или оставлять @objc?

2021-11-10 21:32 UTC, marinamarinat commented on magic 8 ball/view controllers/SettingsViewController.swift
>      static var answers:[String] = []
если убрать static:
Instance member 'answers' cannot be used on type 'SettingsViewController'; did you mean to use a value of this type instead?

2021-11-11 08:54 UTC, ios-school-yalantis commented on magic 8 ball/view controllers/SettingsViewController.swift
>      static var answers:[String] = []
правильно, нужно переделать способ обращения к данным тоже, не должно быть статик проперти в контроллерах

2021-11-11 08:56 UTC, ios-school-yalantis requested changes

2021-11-11 08:56 UTC, ios-school-yalantis commented on magic 8 ball/view controllers/AlertController.swift
> +    @objc func showAddAnswerAlert() {
можно оставить `@objc`

2021-11-11 10:27 UTC, marinamarinat commented on magic 8 ball/view controllers/SettingsViewController.swift
>      static var answers:[String] = []
исправила)

2021-11-11 10:33 UTC, ios-school-yalantis approved these changes
можно мержить

2021-11-11 10:51 UTC, merged